version: 2.0
jobs:
    
    "all-py37-cu100_all-py37-_all_py37-cu100_latest":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py37-cu100 -t $DOCKER_REPO:all-py37- -t $DOCKER_REPO:all -t $DOCKER_REPO:py37-cu100 -t $DOCKER_REPO:latest -f docker/Dockerfile.all-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py37-cu100            
            - run: docker push $DOCKER_REPO:all-py37-            
            - run: docker push $DOCKER_REPO:all            
            - run: docker push $DOCKER_REPO:py37-cu100            
            - run: docker push $DOCKER_REPO:latest
    
    "tensorflow-py37-cpu_tensorflow-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py37-cpu -t $DOCKER_REPO:tensorflow-cpu -f docker/Dockerfile.tensorflow-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py37-cpu            
            - run: docker push $DOCKER_REPO:tensorflow-cpu
    
    "all-py37-cpu_all-cpu_py37-cpu_cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-py37-cpu -t $DOCKER_REPO:all-cpu -t $DOCKER_REPO:py37-cpu -t $DOCKER_REPO:cpu -f docker/Dockerfile.all-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-py37-cpu            
            - run: docker push $DOCKER_REPO:all-cpu            
            - run: docker push $DOCKER_REPO:py37-cpu            
            - run: docker push $DOCKER_REPO:cpu
    
    "pytorch-py37-cu100_pytorch-py37-_pytorch":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py37-cu100 -t $DOCKER_REPO:pytorch-py37- -t $DOCKER_REPO:pytorch -f docker/Dockerfile.pytorch-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py37-cu100            
            - run: docker push $DOCKER_REPO:pytorch-py37-            
            - run: docker push $DOCKER_REPO:pytorch
    
    "spacy-py37-cu100_spacy-py37-_spacy":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:spacy-py37-cu100 -t $DOCKER_REPO:spacy-py37- -t $DOCKER_REPO:spacy -f docker/Dockerfile.spacy-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:spacy-py37-cu100            
            - run: docker push $DOCKER_REPO:spacy-py37-            
            - run: docker push $DOCKER_REPO:spacy
    
    "tensorflow-py37-cu100_tensorflow-py37-_tensorflow":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:tensorflow-py37-cu100 -t $DOCKER_REPO:tensorflow-py37- -t $DOCKER_REPO:tensorflow -f docker/Dockerfile.tensorflow-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:tensorflow-py37-cu100            
            - run: docker push $DOCKER_REPO:tensorflow-py37-            
            - run: docker push $DOCKER_REPO:tensorflow
    
    "keras-py37-cpu_keras-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py37-cpu -t $DOCKER_REPO:keras-cpu -f docker/Dockerfile.keras-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py37-cpu            
            - run: docker push $DOCKER_REPO:keras-cpu
    
    "keras-py37-cu100_keras-py37-_keras":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:keras-py37-cu100 -t $DOCKER_REPO:keras-py37- -t $DOCKER_REPO:keras -f docker/Dockerfile.keras-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:keras-py37-cu100            
            - run: docker push $DOCKER_REPO:keras-py37-            
            - run: docker push $DOCKER_REPO:keras
    
    "spacy-py37-cpu_spacy-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:spacy-py37-cpu -t $DOCKER_REPO:spacy-cpu -f docker/Dockerfile.spacy-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:spacy-py37-cpu            
            - run: docker push $DOCKER_REPO:spacy-cpu
    
    "all-jupyter-py37-cpu_all-jupyter-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py37-cpu -t $DOCKER_REPO:all-jupyter-cpu -f docker/Dockerfile.all-jupyter-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py37-cpu            
            - run: docker push $DOCKER_REPO:all-jupyter-cpu
    
    "pytorch-py37-cpu_pytorch-cpu":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:pytorch-py37-cpu -t $DOCKER_REPO:pytorch-cpu -f docker/Dockerfile.pytorch-py37-cpu .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:pytorch-py37-cpu            
            - run: docker push $DOCKER_REPO:pytorch-cpu
    
    "all-jupyter-py37-cu100_all-jupyter-py37-_all-jupyter":
        machine: true
        steps:
            - checkout
            - run: docker build -t $DOCKER_REPO:all-jupyter-py37-cu100 -t $DOCKER_REPO:all-jupyter-py37- -t $DOCKER_REPO:all-jupyter -f docker/Dockerfile.all-jupyter-py37-cu100 .
            - run: docker login -u $DOCKER_USER -p $DOCKER_PASS            
            - run: docker push $DOCKER_REPO:all-jupyter-py37-cu100            
            - run: docker push $DOCKER_REPO:all-jupyter-py37-            
            - run: docker push $DOCKER_REPO:all-jupyter

workflows:
    version: 2
    build:
        jobs:
            - "all-py37-cu100_all-py37-_all_py37-cu100_latest"
            - "tensorflow-py37-cpu_tensorflow-cpu"
            - "all-py37-cpu_all-cpu_py37-cpu_cpu"
            - "pytorch-py37-cu100_pytorch-py37-_pytorch"
            - "spacy-py37-cu100_spacy-py37-_spacy"
            - "tensorflow-py37-cu100_tensorflow-py37-_tensorflow"
            - "keras-py37-cpu_keras-cpu"
            - "keras-py37-cu100_keras-py37-_keras"
            - "spacy-py37-cpu_spacy-cpu"
            - "all-jupyter-py37-cpu_all-jupyter-cpu"
            - "pytorch-py37-cpu_pytorch-cpu"
            - "all-jupyter-py37-cu100_all-jupyter-py37-_all-jupyter"